#analytics:
#  container_name: analytics
#  image: florentpeyron/twitter-analytics:latest
#  ports:
#   - "8761:8761"
graphdb:
  container_name: graphdb
  image: neo4j:latest
  environment:
    - NEO4J_AUTH=none
  cap_add:
    - SYS_RESOURCE
  ports:
    - "7474:7474"
rabbit:
  container_name: rabbit
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
    - "5672:5672"
