graphdb:
  container_name: graphdb
  image: neo4j:latest
  environment:
    - NEO4J_AUTH=none
  cap_add:
    - SYS_RESOURCE
  ports:
    - "7474:7474"

rabbitmq:
  container_name: rabbitmq
  image: rabbitmq:3-management
  ports:
    - "15672:15672"
    - "5672:5672"
