server:
  port: 8080
  servletPath: /
spring:

  neo4j:
    port: 7474
    host: '192.168.99.100'

  rabbitmq:
    port: 5672
    host: '192.168.99.100'
    username: guest
    password: guest
    listener:
      max-concurrency: 1
      prefetch: 1
      acknowledge-mode: auto
      auto-startup: true
    dynamic: true

  social:
    twitter:
      accessTokenSecret: 'AoY0FBwWDqQS1kbZhayoQXv8qBPTDgdOnLJPRd9CyDSuF'
      accessToken: '204036760-yzYcxXRKIIVo3o9GZNTaEito1E1YyuXu77HjIJxR'
      appSecret: 'QiQWpVzXWNxlRiduzkyer2WXheihP6dVr04Z3UHmnSMeEs5M2W'
      appId: 'J2kuUaDqpdW020Jzmn603oC7U'